- name: create folder - {{ item.dir }}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://52.23.248.230:8080/
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: Create Pipeline Jobs file
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

