- name: create folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.83.107:8080/
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: Create Multi Pipeline Jobs file
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

- name: Create single Pipeline Jobs file
  ansible.builtin.include_tasks: sbranch-pipeline.yml
  loop: "{{ sbranch_pipeline_jobs }}"

