- name: create folder - {{ item.dir }}
  community.general.jenkins_jobs:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item}}"
    url: http://52.23.248.230:8080/
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: Create Pipeline Jobs file
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ pipeline_jobs }}"

