- name: create folder config file
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.dir}}"
    url: http://52.23.248.230:8080/
    user: admin
    password: "{{jenkins_password}}"

- name: create config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml


- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://52.23.248.230:8080/
    user: admin
    password: "{{jenkins_password}}"
