- name: create config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml


- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://52.23.248.230:8080/
    user: admin
    password: "{{jenkins_password}}"
